//
//  EditNoteViewController.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditNoteDisplayLogic: class
{
  func displayNoteToEdit(viewModel: EditNote.OpenNote.ViewModel)
  func displayUpdatedNote(viewModel: EditNote.UpdateNote.ViewModel)
}

class EditNoteViewController: UIViewController, EditNoteDisplayLogic
{
  var interactor: EditNoteBusinessLogic?
  var router: (NSObjectProtocol & EditNoteRoutingLogic & EditNoteDataPassing)?
  var isRecycling = false
  @IBOutlet private lazy var recycleButton: UIBarButtonItem? = {
    let rb = UIBarButtonItem(image: UIImage(systemName: "arrow.3.trianglepath"), style: .plain, target: self, action: #selector(recycleButtonPressed(_:)))
    return rb
  }()
  @IBOutlet private lazy var deleteButton: UIBarButtonItem? = {
    let db = UIBarButtonItem(barButtonSystemItem: .trash, target: self, action: #selector(deleteButtonPressed(_:)))
    return db
  }()
  @IBOutlet private lazy var composeButton: UIBarButtonItem? = {
    let cb = UIBarButtonItem(barButtonSystemItem: .compose, target: self, action: #selector(composeButtonPressed(_:)))
    return cb
  }()
  @IBOutlet private lazy var restoreButton: UIBarButtonItem? = {
    let rb = UIBarButtonItem(image: UIImage(systemName: "arrow.uturn.up.square"), style: .plain, target: self, action: #selector(restoreButtonPressed(_:)))
    return rb
  }()
  
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = EditNoteInteractor()
    let presenter = EditNotePresenter()
    let router = EditNoteRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier
    {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector)
      {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewWillAppear(_ animated: Bool)
  {
    super.viewWillAppear(animated)
    setupButtons()
  }
  
  override func viewDidAppear(_ animated: Bool)
  {
    super.viewDidAppear(animated)
    
    if !isRecycling
    {
      textView.becomeFirstResponder()
    }
  }
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    openNoteToEdit()
  }
  
  private func setupButtons()
  {
    if isRecycling
    {
      guard let db = deleteButton, let rb = restoreButton else
      {
        // TODO: How could this happen?
        return
      }
      
      navigationItem.rightBarButtonItems = [rb, db]
    }
    else
    {
      guard let cb = composeButton, let rb = recycleButton else
      {
        // TODO: How could this happen?
        return
      }
      
      navigationItem.rightBarButtonItems = [cb, rb]
    }
  }
  
  // MARK: Do something
  
  func openNoteToEdit()
  {
    let request = EditNote.OpenNote.Request()
    interactor?.openNote(request: request)
  }
  
  @IBOutlet var textView: UITextView!
  
  func saveNote(content: String)
  {
    let request = EditNote.UpdateNote.Request(content: content)
    interactor?.updateNote(request: request)
  }
  
  func displayNoteToEdit(viewModel: EditNote.OpenNote.ViewModel)
  {
    DispatchQueue.main.async {
      self.textView.text = viewModel.content
      self.title = viewModel.title
    }
  }
  
  func displayUpdatedNote(viewModel: EditNote.UpdateNote.ViewModel)
  {
    DispatchQueue.main.async {
      self.title = viewModel.note?.title
      // Ignore the note's content, since the content is being edited actively here
    }
  }
  
  @IBAction func recycleButtonPressed(_ sender: Any)
  {
    let request = EditNote.RecycleNote.Request()
    interactor?.recycleNote(request: request)
    router?.routeToListNotes(segue: nil)
  }
  
  @IBAction func deleteButtonPressed(_ sender: Any)
  {
    let request = EditNote.DeleteNote.Request()
    interactor?.deleteNote(request: request)
    router?.routeToListNotes(segue: nil)
  }
  
  @IBAction func composeButtonPressed(_ sender: Any)
  {
    let request = EditNote.CreateNote.Request()
    interactor?.createNote(request: request)
  }
  
  @IBAction func restoreButtonPressed(_ sender: Any)
  {
    let request = EditNote.RestoreNote.Request()
    interactor?.restoreNote(request: request)
    router?.routeToListNotes(segue: nil)
  }
}

extension EditNoteViewController: UITextViewDelegate
{
  func textViewDidChange(_ textView: UITextView)
  {
    let request = EditNote.UpdateNote.Request(content: textView.text)
    interactor?.updateNote(request: request)
  }
}
