//
//  EditNoteInteractor.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditNoteBusinessLogic
{
  func doSomething(request: EditNote.EditNote.Request)
}

protocol EditNoteDataStore
{
  //var name: String { get set }
}

class EditNoteInteractor: EditNoteBusinessLogic, EditNoteDataStore
{
  var presenter: EditNotePresentationLogic?
  var worker: EditNoteWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: EditNote.EditNote.Request)
  {
    worker = EditNoteWorker()
    worker?.doSomeWork()
    
    let response = EditNote.EditNote.Response()
    presenter?.presentNoteToEdit(response: response)
  }
}
