//
//  EditNoteRouter.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EditNoteRoutingLogic
{
  func routeToListNotes(segue: UIStoryboardSegue?)
}

protocol EditNoteDataPassing
{
  var dataStore: EditNoteDataStore? { get }
}

class EditNoteRouter: NSObject, EditNoteRoutingLogic, EditNoteDataPassing
{
  weak var viewController: EditNoteViewController?
  var dataStore: EditNoteDataStore?
  
  // MARK: Routing
  
  func routeToListNotes(segue: UIStoryboardSegue?)
  {
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  }

  // MARK: Navigation
  
  func navigateToListNotes(source: EditNoteViewController, destination: ListNotesViewController)
  {
    source.navigationController?.popViewController(animated: true)
  }
  
  // MARK: Passing data
  
  func passDataToListNotes(source: EditNoteDataStore, destination: inout ListNotesDataStore)
  {
//    destination.name = source.name
  }
}
