//
//  CreateNoteInteractor.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateNoteBusinessLogic
{
  func doSomething(request: CreateNote.Something.Request)
}

protocol CreateNoteDataStore
{
  //var name: String { get set }
}

class CreateNoteInteractor: CreateNoteBusinessLogic, CreateNoteDataStore
{
  var presenter: CreateNotePresentationLogic?
  var worker: CreateNoteWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CreateNote.Something.Request)
  {
    worker = CreateNoteWorker()
    worker?.doSomeWork()
    
    let response = CreateNote.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
