//
//  CreateNotePresenter.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateNotePresentationLogic
{
  func presentSomething(response: CreateNote.Something.Response)
}

class CreateNotePresenter: CreateNotePresentationLogic
{
  weak var viewController: CreateNoteDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CreateNote.Something.Response)
  {
    let viewModel = CreateNote.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
