//
//  ListNotesPresenter.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListNotesPresentationLogic
{
  func presentFetchedNotes(response: ListNotes.FetchNotes.Response)
  func presentCreatedNote(response: ListNotes.CreateNote.Response)
  
  // Do Nothing
  func presentEmptyRecycleBin(response: ListNotes.EmptyRecycleBin.Response)
}

class ListNotesPresenter: ListNotesPresentationLogic
{
  weak var viewController: ListNotesDisplayLogic?
  
  private let dateFormatter: DateFormatter = {
    let df = DateFormatter()
    df.dateStyle = .short
    df.timeStyle = .short
    
    return df
  }()
  
  // MARK: Do something
  
  private func prepareForListDisplay(note: Note?) -> ListNotes.DisplayedNote?
  {
    guard let n = note else
    {
      return nil
    }
    
    let date = dateFormatter.string(from: n.date)
    
    return ListNotes.DisplayedNote(id: n.id ?? "", date: date, title: n.title)
  }
  
  func presentFetchedNotes(response: ListNotes.FetchNotes.Response)
  {
    let notesToDisplay = response.notes.compactMap({ self.prepareForListDisplay(note: $0) })
    
    // TODO: Move this code out to ListFolders scene (Presenter) when multiple folders are supported.
    let folderTitle: String
    
    switch response.folder
    {
    case .RecycleBin: folderTitle = NSLocalizedString("Recycle Bin", comment: "")
    case .Working(let folderName): folderTitle = NSLocalizedString(folderName, comment: "")
    }
    
    let viewModel = ListNotes.FetchNotes.ViewModel(folderTitle: folderTitle, displayedNotes: notesToDisplay)
    viewController?.displayFetchedNotes(viewModel: viewModel)
  }
  
  func presentCreatedNote(response: ListNotes.CreateNote.Response)
  {
    let noteForDisplay = prepareForListDisplay(note: response.note)
    let vm = ListNotes.CreateNote.ViewModel(displayedNote: noteForDisplay)
    viewController?.displayCreatedNote(viewModel: vm)
  }
  
  func presentEmptyRecycleBin(response: ListNotes.EmptyRecycleBin.Response)
  {
    let vm = ListNotes.EmptyRecycleBin.ViewModel()
    viewController?.displayEmptyRecycleBin(viewModel: vm)
  }
}
