//
//  ListFoldersRouter.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListFoldersRoutingLogic
{
  func routeToMainFolder(segue: UIStoryboardSegue?)
  func routeToRecycleBin(segue: UIStoryboardSegue?)
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

// TODO: Currently only have 2 hard coded folders, so leave this unused
protocol ListFoldersDataPassing
{
  var dataStore: ListFoldersDataStore? { get }
}

class ListFoldersRouter: NSObject, ListFoldersRoutingLogic, ListFoldersDataPassing
{
  weak var viewController: ListFoldersViewController?
  var dataStore: ListFoldersDataStore?
  
  // MARK: Routing
  
  func routeToMainFolder(segue: UIStoryboardSegue?)
  {
    guard let myDS = dataStore, let vc = viewController else
    {
      // TODO: Handle missing piece error
      return
    }
    
    if let segue = segue, let destinationVC = segue.destination as? ListNotesViewController,
      var destinationDS = destinationVC.router?.dataStore
    {
      
      passDataToMainFolder(source: myDS, destination: &destinationDS)
      navigateToMainFolder(source: vc, destination: destinationVC)
    }
  }
  
  func routeToRecycleBin(segue: UIStoryboardSegue?)
  {
    
  }
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}
  
  // MARK: Navigation
  
  //func navigateToSomewhere(source: ListFoldersViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  func navigateToMainFolder(source: ListFoldersViewController, destination: ListNotesViewController)
  {
    
  }
  
  func navigateToRecycleBin(source: ListFoldersViewController, destination: ListNotesViewController)
  {
    
  }
  
  // MARK: Passing data
  
  func passDataToMainFolder(source: ListFoldersDataStore, destination: inout ListNotesDataStore)
  {
    //destination.name = source.name
    destination.folder = ListNotes.Folder.Inbox
  }
  
  func passDataToRecycleBin(source: ListFoldersDataStore, destination: inout ListNotesDataStore)
  {
    destination.folder = ListNotes.Folder.RecycleBin
  }
}
