//
//  ListFoldersPresenter.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListFoldersPresentationLogic
{
//  func presentSomething(response: ListFolders.Something.Response)
}

class ListFoldersPresenter: ListFoldersPresentationLogic
{
//  weak var viewController: ListFoldersDisplayLogic?
//
//  // MARK: Do something
//
//  func presentSomething(response: ListFolders.Something.Response)
//  {
//    let viewModel = ListFolders.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
}
