//
//  ListNotesRouter.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListNotesRoutingLogic
{
  func routeToEditNote(segue: UIStoryboardSegue?)
  func routeToComposeNote(segue: UIStoryboardSegue?)
}

protocol ListNotesDataPassing
{
  var dataStore: ListNotesDataStore? { get }
}

class ListNotesRouter: NSObject, ListNotesRoutingLogic, ListNotesDataPassing
{
  weak var viewController: ListNotesViewController?
  var dataStore: ListNotesDataStore?
  
  // MARK: Routing
  
  func routeToEditNote(segue: UIStoryboardSegue?)
  {
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  }

  func routeToComposeNote(segue: UIStoryboardSegue?)
  {
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  }
  
  // MARK: Navigation
  
  func navigateToEditNote(source: ListNotesViewController, destination: EditNoteViewController)
  {
    
  }
  
  func navigateToComposeNote(source: ListNotesViewController, destination: EditNoteViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToEditNote(source: ListNotesDataStore, destination: inout EditNoteDataStore)
  {
//    destination.name = source.name
  }
  
  func passDataToComposeNote(source: ListNotesDataStore, destination: inout EditNoteDataStore)
    {
  //    destination.name = source.name
    }
    
    
}
