//
//  ListNotesPresenter.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListNotesPresentationLogic
{
  func presentSomething(response: ListNotes.Something.Response)
}

class ListNotesPresenter: ListNotesPresentationLogic
{
  weak var viewController: ListNotesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListNotes.Something.Response)
  {
    let viewModel = ListNotes.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
