//
//  ListNotesInteractor.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListNotesBusinessLogic
{
  func fetchNotes(request: ListNotes.FetchNotes.Request)
}

protocol ListNotesDataStore
{
  //var name: String { get set }
}

class ListNotesInteractor: ListNotesBusinessLogic, ListNotesDataStore
{
  var presenter: ListNotesPresentationLogic?
  var worker: ListNotesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func fetchNotes(request: ListNotes.FetchNotes.Request)
  {
    worker = ListNotesWorker()
    worker?.doSomeWork()
    
    let response = ListNotes.FetchNotes.Response()
    presenter?.presentFetchedNotes(response: response)
  }
}
