//
//  ListNotesViewController.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListNotesDisplayLogic: class
{
  func displayFetchedNotes(viewModel: ListNotes.FetchNotes.ViewModel)
}

class ListNotesViewController: UITableViewController, ListNotesDisplayLogic
{
  var interactor: ListNotesBusinessLogic?
  //var folder: ListNotes.Folder = .Working("Inbox") // FIXME:
  var router: (NSObjectProtocol & ListNotesRoutingLogic & ListNotesDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ListNotesInteractor()
    let presenter = ListNotesPresenter()
    let router = ListNotesRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewWillAppear(_ animated: Bool)
  {
    super.viewWillAppear(animated)
    fetchNotesOnLoad()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func fetchNotesOnLoad()
  {
    let request = ListNotes.FetchNotes.Request()
    interactor?.fetchNotes(request: request)
  }
  
  func displayFetchedNotes(viewModel: ListNotes.FetchNotes.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
