//
//  ListNotesModels.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListNotes
{
  enum Folder : Equatable
  {
    case RecycleBin
    case Working(String)
    
    static func ==(lhs: Folder, rhs: Folder) -> Bool
    {
      switch (lhs, rhs)
      {
      case (.RecycleBin, .RecycleBin): return true
      case (.Working(let a), .Working(let b)): return a == b
      default: return false
      }
    }
    
    static let Inbox = Working("Inbox")
  }
  
  // MARK: Use cases
  
  enum FetchNotes
  {
    struct Request
    {
      //let folder: Folder
    }
    struct Response
    {
      let notes: [Note]
    }
    struct ViewModel
    {
      struct DisplayedNote
      {
        var id: String
        var date: String
        var title: String
//        var content: String
      }
      
      var displayedNotes: [DisplayedNote]
    }
  }
}
