//
//  ListNotesWorker.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListNotesWorker
{
  var notesStore: NotesStoreProtocol
  
  init(store: NotesStoreProtocol)
  {
    notesStore = store
  }
  
  func fetchNotes(in folder: Folder, completionHandler: @escaping ([Note]) -> Void)
  {
    notesStore.fetchNotes(in: folder) { (result: Result<[Note], QNotesError>) -> Void in
      
      switch result
      {
      case let .success(notes):
        DispatchQueue.main.async {
          completionHandler(notes)
        }
      case let .failure(error):
        DispatchQueue.main.async {
          
          completionHandler([])
        }
      }
    }
  }
}
