//
//  ListNotesRouter.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListNotesRoutingLogic
{
  func routeToEditNote(segue: UIStoryboardSegue?)
  func routeToComposeNote(segue: UIStoryboardSegue?)
}

protocol ListNotesDataPassing
{
  var dataStore: ListNotesDataStore? { get }
}

class ListNotesRouter: NSObject, ListNotesRoutingLogic, ListNotesDataPassing
{
  weak var viewController: ListNotesViewController?
  var dataStore: ListNotesDataStore?
  
  // MARK: Routing
  
  func routeToEditNote(segue: UIStoryboardSegue?)
  {
    if let segue = segue
    {
      // FIXME: Hackish
      guard let destinationVC = segue.destination as? EditNoteViewController ?? ((segue.destination as? UINavigationController)?.viewControllers.first as? EditNoteViewController) else
      {
        fatalError("Couldn't reach the EditNoteViewController on the other side")
      }
        
      guard let ds = dataStore, var destinationDS = destinationVC.router?.dataStore else
      {
        fatalError("Couldn't find the ListNotesRouter's dataStore or the Editor's dataStore")
      }
      
      passDataToEditNote(source: ds, destination: &destinationDS)
    } else {
      // TODO!
    }
  }
    
  func routeToComposeNote(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! EditNoteViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToComposeNote(source: dataStore!, destination: &destinationDS)
    } else {
//      let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "ShowOrderViewController") as! ShowOrderViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToShowOrder(source: dataStore!, destination: &destinationDS)
//      navigateToShowOrder(source: viewController!, destination: destinationVC)
    }
  }
  
  // MARK: Navigation
  
  func navigateToEditNote(source: ListNotesViewController, destination: EditNoteViewController)
  {
    
  }
  
  func navigateToComposeNote(source: ListNotesViewController, destination: EditNoteViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToEditNote(source: ListNotesDataStore, destination: inout EditNoteDataStore)
  {
    guard let idx = viewController?.tableView.indexPathForSelectedRow?.row,
      idx >= 0, idx < source.notes.count else
    {
      viewController?.showErrorMessage(title: "Can't find note to open", message: "Couldn't open note in row \(String(describing: viewController?.tableView.indexPathForSelectedRow?.row)) out of \(source.notes.count) rows")
      
      return
    }
    
    destination.note = source.notes[idx]
  }
  
  func passDataToComposeNote(source: ListNotesDataStore, destination: inout EditNoteDataStore)
  {
    destination.note = source.notes[0] // New note; edit the top-most one
  }
}
