//
//  ListNotesPresenter.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListNotesPresentationLogic
{
  func presentFetchedNotes(response: ListNotes.FetchNotes.Response)
}

class ListNotesPresenter: ListNotesPresentationLogic
{
  weak var viewController: ListNotesDisplayLogic?
  
  let dateFormatter: DateFormatter = {
    let df = DateFormatter()
    df.dateStyle = .short
    df.timeStyle = .short
    
    return df
  }()
  
  // MARK: Do something
  
  func presentFetchedNotes(response: ListNotes.FetchNotes.Response)
  {
    // TODO: Convert
    let notesToDisplay = response.notes.map { (note: Note) -> ListNotes.FetchNotes.ViewModel.DisplayedNote in
      let date = dateFormatter.string(from: note.date)
      
      return ListNotes.FetchNotes.ViewModel.DisplayedNote(id: note.id ?? "", date: date, title: note.title)
    }
    
    
    let viewModel = ListNotes.FetchNotes.ViewModel(displayedNotes: notesToDisplay)
    viewController?.displayFetchedNotes(viewModel: viewModel)
  }
}
