//
//  RecycleBinPresenter.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecycleBinPresentationLogic
{
  func presentSomething(response: RecycleBin.Something.Response)
}

class RecycleBinPresenter: RecycleBinPresentationLogic
{
  weak var viewController: RecycleBinDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: RecycleBin.Something.Response)
  {
    let viewModel = RecycleBin.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
