//
//  RecycleBinInteractor.swift
//  QNotes
//
//  Created by Meir Radnovich on 01/01/2020.
//  Copyright (c) 2020 Meir Radnovich. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecycleBinBusinessLogic
{
  func doSomething(request: RecycleBin.Something.Request)
}

protocol RecycleBinDataStore
{
  //var name: String { get set }
}

class RecycleBinInteractor: RecycleBinBusinessLogic, RecycleBinDataStore
{
  var presenter: RecycleBinPresentationLogic?
  var worker: RecycleBinWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: RecycleBin.Something.Request)
  {
    worker = RecycleBinWorker()
    worker?.doSomeWork()
    
    let response = RecycleBin.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
